"""Surveillance constants."""

# Status codes
SURVEILLANCE_STATUS_ACTIVE = "active"
SURVEILLANCE_STATUS_INACTIVE = "inactive"
SURVEILLANCE_STATUS_PENDING = "pending"
SURVEILLANCE_STATUS_ERROR = "error"

# Limits
SURVEILLANCE_MAX_BATCH_SIZE = 1000
SURVEILLANCE_DEFAULT_TIMEOUT = 30
SURVEILLANCE_MAX_RETRIES = 3
SURVEILLANCE_CACHE_TTL = 300

# Field names
SURVEILLANCE_FIELDS = [
    "id", "name", "type", "status",
    "metadata", "created_at", "updated_at",
]

ALL_STATUSES = [
    SURVEILLANCE_STATUS_ACTIVE,
    SURVEILLANCE_STATUS_INACTIVE,
    SURVEILLANCE_STATUS_PENDING,
    SURVEILLANCE_STATUS_ERROR,
]
