apiVersion: v1
kind: Service
metadata:
  name: malaria-forecasting
spec:
  selector: { app: malaria-forecasting }
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP