version: "3.9"
services:
  api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    env_file: ../../.env
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: malaria_user
      POSTGRES_PASSWORD: malaria_pass
      POSTGRES_DB: malaria
    ports:
      - "5432:5432"